import assert from 'node:assert/strict';
import {simulate,coordinate} from '../lib/sustain.ts';
const root='http://127.0.0.1:5173';
const page=await fetch(root);assert.equal(page.status,200);const html=await page.text();assert.ok(html.includes('SustainAI'));console.log('Initial route renders correctly.');
for(const path of ['map','locations','predictions','what-if','assistant','plans','goals','sources','profile']){const r=await fetch(`${root}/${path}`);assert.equal(r.status,200,`${path} must render`);}console.log('All ten pages render.');
const invalid=await fetch(`${root}/api/sustain?op=data&lat=91&lon=0`);assert.notEqual(invalid.status,200);
const coords=await fetch(`${root}/api/sustain?op=search&q=12.345%2C-45.678`).then(r=>r.json());assert.equal(coords.places[0].lat,12.345);assert.equal(coords.places[0].lon,-45.678);
assert.throws(()=>coordinate(null,0));assert.throws(()=>coordinate(0,181));
assert.deepEqual(simulate({water:1000,energy:200,distance:100,factor:0.5,vehicleFactor:0.2},{water:20,energy:15,transport:25}),{waterSaved:200,energySaved:30,distanceAvoided:25,emissionsAvoided:20});console.log('Coordinate validation and independent scenario calculation pass.');
const auth=await fetch(`${root}/signin-with-chatgpt?return_to=/`,{redirect:'manual'});const cookies=auth.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ');assert.ok(cookies,'Local mock sign-in cookie');
const headers={'Content-Type':'application/json',Origin:root,Cookie:cookies};
const saved=await fetch(`${root}/api/sustain`,{method:'POST',headers,body:JSON.stringify({op:'save',kind:'goal',payload:{title:'Runtime QA fixture',target:100,progress:0,category:'Water',unit:'L',date:'2027-01-01',locKey:'qa',history:[]}})});const s=await saved.json();assert.equal(saved.status,200,JSON.stringify(s));
let rows=await fetch(`${root}/api/sustain?op=records`,{headers:{Cookie:cookies}}).then(r=>r.json());assert.ok(rows.records.some(r=>r.id===s.id));
const changed=await fetch(`${root}/api/sustain`,{method:'POST',headers,body:JSON.stringify({op:'save',id:s.id,kind:'goal',payload:{title:'Runtime QA fixture',target:100,progress:50,category:'Water',unit:'L',date:'2027-01-01',locKey:'qa',history:[]}})});assert.equal(changed.status,200);
rows=await fetch(`${root}/api/sustain?op=records`,{headers:{Cookie:cookies}}).then(r=>r.json());assert.equal(rows.records.find(r=>r.id===s.id).payload.progress,50);
assert.equal((await fetch(`${root}/api/sustain`,{method:'POST',headers:{...headers,Origin:'https://wrong.example'},body:'{}'})).status,403);
assert.equal((await fetch(`${root}/api/sustain`,{method:'POST',headers,body:JSON.stringify({op:'save',id:crypto.randomUUID(),kind:'plan',payload:{}})})).status,404);
await fetch(`${root}/api/sustain`,{method:'POST',headers,body:JSON.stringify({op:'delete',id:s.id})});console.log('Persistent create, reload, update, delete and request authorization pass.');
const search=await fetch(`${root}/api/sustain?op=search&q=Oslo`).then(r=>r.json());assert.ok(search.places?.length,JSON.stringify(search));console.log('Worldwide provider geocoding returns real results.');
const data=await fetch(`${root}/api/sustain?op=data&lat=${search.places[0].lat}&lon=${search.places[0].lon}`).then(r=>r.json());assert.ok(data.weather?.daily?.time?.length===7,JSON.stringify(data.errors));assert.ok(data.air?.current);assert.ok(data.fetchedAt);console.log('Verified weather and air-quality fetch returns provenance and seven-day forecast.');
